### ISSUE TITLE
Auto updating progress bar

### ISSUE THREAD

**Issue by Ashesh3** [mariusbegby/cadence-discord-bot#337]
The current progress bar looks really neat, but it would be more helpful to update the progress bar in real time (or every x seconds). This can be achieved by keeping track of the "latest" now playing embed (only the latest one would be enough too ) and editing it every x seconds to reflect the current progress of the song.

![image](https://github.com/mariusbegby/cadence-discord-bot/assets/3626859/266ffeec-9d0e-4362-bbed-07cf27a506df)

**Comment by GokulSamraj** [comment]
It seems to be a cool idea but is this developer even sees the issues and working for the fixes?

**Comment by mariusbegby** [comment]
@GokulSamraj I am tracking issues and people are free to report bugs and issues they find.

However, I only work on this project as a hobby, and the past months I've been busy with my thesis.

You are free to submit a PR if you want to fix issues faster. Otherwise, feel free to use another bot.

**Comment by LakhindarPal** [comment]
While this is a cool idea, you may reconsider this before implementing. As if you constantly keep updating the message, you may hit a rate limit.

**Comment by twlite** [comment]
Pretty sure discord.js handles ratelimits and if needed you can debounce the update by few seconds.
If you wanna make this look cooler, spice it up with [synced lyrics](https://github.com/Androz2091/discord-player/blob/stable/apps/music-bot/src/commands/lyrics.ts#L31-L54). Synced lyrics provider ticks every second internally but it would not fire every second (tbh it depends on the song)

**Comment by mariusbegby** [comment]
This will most likely not be implemented, but feel free to fork and create your own functionality around this if you need it.
