### ISSUE TITLE
Ability to change search engine on /play

### ISSUE THREAD

**Issue by qqawsedr8** [mariusbegby/cadence-discord-bot#385]
I think the ability to change the search engine to Spotify or Youtube or any other available extractor would be an important option to have either globally or as a parameter on the /play command

**Comment by mariusbegby** [comment]
Could be made as a configurable option with the persistent config coming in v6.

And also done with prefix on search queries, e.g. /play yt:query will only query youtube search results.

Will look into this for v6.

**Comment by qqawsedr8** [comment]
Is there something I can change in the code to use Youtube for the meantime until this gets implemented, or is it something major that cannot be done at this moment?

**Comment by mariusbegby** [comment]
@qqawsedr8 yes you can do this. Cadence uses `discord-player` as a dependency which allows you to change search engine: <https://discord-player.js.org/docs/discord-player/type/PlayerNodeInitializerOptions>

You can add `searchEngine: QueryType.YOUTUBE` (remember to import `QueryType` from `discord-player`) during player.play() method. For example:
```ts
({ track } = await player.play((interaction.member as GuildMember).voice.channel!, searchResult, {
    requestedBy: interaction.user,
    searchEngine: QueryType.YOUTUBE,
    nodeOptions: {
        ...this.playerOptions,
        maxSize: this.playerOptions.maxQueueSize,
        volume: this.playerOptions.defaultVolume,
        metadata: {
            channel: interaction.channel,
            client: interaction.client,
            requestedBy: interaction.user
        }
    }
}));
```

**Comment by qqawsedr8** [comment]
Will do. Thank you for the reply!

**Comment by qqawsedr8** [comment]
Do note that I had to add that parameter to the player.search on the searchTrack method or else it was still using Spotify to search. Just a heads-up

**Comment by mariusbegby** [comment]
Yes that is correct, anywhere the player performs a search this option needs to be passed. I have written a note for this improvement to be included in future release.

**Comment by qqawsedr8** [comment]
It would seem that the search results that appear are still from another extractor. I solved this by adding `await player.extractors.register(YouTubeExtractor, {});` above `await player.extractors.loadDefault();` on createPlayer.ts

**Comment by mariusbegby** [comment]
It could be a fallback if no result is found. You can also set fallbackSearchEngine.

There should be 3 ways to achieve searching from only one or multiple specific sources:
- Provide specific searchEngine and fallbackSearchEngine in PlayerNodeInitializerOptions during search.
- On startup, register only the extractors to be used in search, then set searchEngine to AUTO in PlayerNodeInitializerOptions. (your most recent comment).
- On startup, set blockStreamFrom in PlayerInitOptions to blacklist certain sources.

Hopefully you get something working. And then I will add an easier config option for this later.

**Comment by qqawsedr8** [comment]
Like I said, the second option worked for me. Since that is enough for my specific use case, I don't want to trouble you anymore. I will wait for the new release for any new features.

**Comment by twlite** [comment]
You can simply prefix your search query with `youtube:`/`spotify:`/`soundcloud:`/`applemusic:` etc to change search engine. For example

```
/play soundcloud:some song
```

This will play from soundcloud.

Here's a table
![image](https://github.com/mariusbegby/cadence-discord-bot/assets/46562212/b49929b6-10b0-470e-a997-0c57e4e7a2b0)

**Comment by qqawsedr8** [comment]
> You can simply prefix your search query with `youtube:`/`spotify:`/`soundcloud:`/`applemusic:` etc to change search engine. For example
> 
> ```
> /play soundcloud:some song
> ```
> 
> This will play from soundcloud.
> 
> Here's a table ![image](https://private-user-images.githubusercontent.com/46562212/317952479-b49929b6-10b0-470e-a997-0c57e4e7a2b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTMzNzQsIm5iZiI6MTcxMTcxMzA3NCwicGF0aCI6Ii80NjU2MjIxMi8zMTc5NTI0NzktYjQ5OTI5YjYtMTBiMC00NzBlLWE5OTctMGM1N2U0ZTdhMmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDExNTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ODgzMjE1ODRmNTNjODk5OTZhMjVjZmJhNzAwZWJmOTVjNjE2YWU1MzAyMjBkMDIyZTFiOTY4NjljZmIyNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OcFBJiXjQZ_A4nYPxMOUqwqqNr2QVvJIcxbPqYPQsJ8)
> 
> This behavior works by default without configuring anything.
> 
> You can do something like
> 
> ```js
> const query = `soundcloud:${interaction.options.getString('query', true)}`
> ```

The first reply to this issue clarified this, but thank you for the table.
