### ISSUE TITLE
Invidious or Piped for download

### ISSUE THREAD

**Issue by qqawsedr8** [mariusbegby/cadence-discord-bot#452]
Is there a way to change the behavior of the play command so it sends an invidious or piped link to the downloader? Grabbing the search results using the normal youtube is fine, just downloading the audio itself is what I'm looking to change.

**Comment by mariusbegby** [comment]
@qqawsedr8 Cadence uses `discord-player`, I'd recommend checking out https://www.npmjs.com/package/discord-player and join their Discord server for help with this: https://discord.gg/androzdev-558328638911545423
